### ISSUE TITLE
Socket errors don't get caught

### ISSUE THREAD

**Issue by TheDevMinerTV** [woodendoors7/MinecraftStatusPinger#1] opened 2023-11-08 22:31 UTC
## Description

The Node.js socket errors don't get caught at the moment and there is no way to do so. Node.js will exit the process when a `EventEmitter` (such as `node:net.Socket`) emits an event called `"error"`.

## Current behaviour

When the code receives a `Connection refused`, it will exit the process.

## Expected behaviour

It throws an error.

## Proposal

Add a hook for the `"error"` socket event and on an error rethrow the error to the caller of `lookup()`.

**Comment by TheDevMinerTV** [comment] 2023-11-08 22:41
I fixed this by patching the `index.ts` file with this:
```diff
diff --git a/dist/index.js b/dist/index.js
index 608a23e75edd07db90aa393eec89a02394c4fdf6..5fd3730a8b6bc5391872d9dda12b89d30c68770d 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -66,8 +66,7 @@ export async function lookup(options) {
         });
         portal.once("error", (netError) => {
             clearTimeout(timeoutFunc);
-            reject();
-            throw netError;
+            reject(netError);
         });
         let timeoutFunc = setTimeout(() => {
             portal.destroy();
```

**Comment by woodendoors7** [comment] 2023-11-08 23:42
Bug fixed in [v1.1.3](https://www.npmjs.com/package/minecraftstatuspinger/v/1.1.3). The bug was caused by a slightly older build being published to NPM in the name of the update that fixed error catching, as such the single throw remained. 

Thanks for pointing this out.

**Closed by woodendoors7** 2023-11-08 23:42 UTC
Labels: bug

**Comment by TheDevMinerTV** [comment] 2023-11-13 17:07
Please reopen, socket timeouts crash the application and cannot be caught in the consumer.

**Comment by woodendoors7** [comment] 2023-11-13 17:32
@TheDevMinerTV You need to update to 1.1.3
